### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zhengxs2018** [zhengxs2018/dingtalk-sdk-for-js#1]
# 待办列表

## 聊天

- [x] 群聊
  - [x] 提及对方
  - [ ] 邀请入群 
  - [ ] 新成员加入
  - [ ] 新成员离开
  - [ ] 群公告
- [x] 私聊

## 通讯录

- [ ] 获取群成员列表
- [ ] 获取指定用户信息

### 接收消息格式

- [x] 文本
- [ ] 富文本
- [ ] 图片
- [ ] 音频
- [ ] 视频
- [ ] 文件

### 发送消息格式

- [x] 文本
- [ ] 图片
- [ ] 音频
- [ ] 视频
- [ ] 文件
- [x] Link
- [x] ActionCard - 由 `@zhengxs/wechaty-dingtalk-message` 提供支持
- [x] Markdown - 由 `@zhengxs/wechaty-dingtalk-message` 提供支持
- [x] FeedCard - 由 `@zhengxs/wechaty-dingtalk-message` 提供支持

### 其他类型消息

- [ ] 消息引用内容

## 互动卡片

- [ ] 接收
- [ ] 发送
- [ ] 更新
